version: "3.9"

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zoo-php
    volumes:
      - app_data:/var/www/html
    restart: unless-stopped
    environment:
      - DATABASE_URL=mysql://symfony:symfony@db:3306/zoo?serverVersion=8&charset=utf8mb4
    depends_on:
      - db

  web:
    image: nginx:latest
    container_name: zoo-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - app_data:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  db:
    image: mysql:8.0
    container_name: zoo-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: zoo
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
  app_data:
